#!/usr/bin/perl

use YAML;

my $work = $ENV{HOME} . "/work";
my $backup = 0;

print "work directory is $work\n\n";

system("maven", "-d", "$work", "ledge:workspace-dependencies") and die "maven invocation failed";

my %deps;
open(DEPS,"$work/dependencies");
while($line = <DEPS>)
{
  chomp($line);
  my ($project,$depstring) = split(':',$line);
  my (@deplist) = split(',',$depstring);
  $deps{$project} = \@deplist;
}

print "updating dependencies...";
my $depcount = 0;

# list the directory
opendir(WORK,$work);
my @projects = sort grep { /^[^\.]/ && -d "$work/$_" } readdir(WORK);
closedir(WORK);
# iterate over all projects
foreach $project (@projects)
{
  my @config = YAML::LoadFile("$work/$project/conf.yaml");
  system("cp","$work/$project/conf.yaml","$work/$project/conf.yaml.bak") if($backup);
  if(defined($deps{$project}))
  {
    ${$config[0]}{'dependent_projects'} = $deps{$project};
    $depcount += $#{$deps{$project}} + 1;
  }
  else
  {
    ${$config[0]}{'dependent_projects'} = ();
  }
  YAML::DumpFile("$work/$project/conf.yaml",@config);
}

print " done.\n";
print "updated $depcount dependencies in " . ($#projects + 1) . " projects\n";
