/* Generated By:JJTree: Do not edit this line. ASTexistencePredicate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.jsonql.impl;

public class ASTexistencePredicate
    extends RelationPredicate
{
    public ASTexistencePredicate(int id)
    {
        super(id);
    }

    public ASTexistencePredicate(JSONQL p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JSONQLVisitor visitor, org.objectledge.jsonql.EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=e3700bc10f2bd213626946e5a7661ee4 (do not edit this line) */
