/* Generated By:JJTree: Do not edit this line. ASTequalityCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.jsonql.impl;

import org.objectledge.jsonql.EvaluationContext;

public class ASTequalityPredicate
    extends SimpleNode
{
    private String value;

    public ASTequalityPredicate(int id)
    {
        super(id);
    }

    public ASTequalityPredicate(JSONQL p, int id)
    {
        super(p, id);
    }

    public String getValue()
    {
        return value;
    }

    public void setValue(Token token)
    {
        this.value = token.image.substring(1, token.image.length() - 1).replaceAll("''", "'");
    }

    @Override
    public String toString()
    {
        return super.toString() + String.format(" = %s", value);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JSONQLVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d480f5860a92d23f3513ee9132562f6a (do not edit this line) */
