/* Generated By:JJTree: Do not edit this line. ASTelementSelection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.jsonql.impl;

import org.objectledge.jsonql.EvaluationContext;

public class ASTelementSelection
    extends SimpleNode
{
    private Kind kind;

    private String identifier;

    private int index;

    public ASTelementSelection(int id)
    {
        super(id);
    }

    public ASTelementSelection(JSONQL p, int id)
    {
        super(p, id);
    }

    public String getIdentifier()
    {
        return identifier;
    }

    public void setIdentifier(Token token)
    {
        this.identifier = token.image;
    }

    public int getIndex()
    {
        return index;
    }

    public void setIndex(Token token)
    {
        this.index = Integer.parseInt(token.image);
    }

    public Kind getKind()
    {
        return kind;
    }

    public void setKind(Kind kind)
    {
        this.kind = kind;
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JSONQLVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }

    public enum Kind
    {
        INDEX, FIELD, PREDICATE
    }
}
/* JavaCC - OriginalChecksum=e37fa8b9a64cd0849475942c19365205 (do not edit this line) */
