/* Generated By:JJTree: Do not edit this line. ASTattributeSelection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.jsonql.impl;

import org.objectledge.jsonql.EvaluationContext;

public class ASTfieldSelection
    extends SimpleNode
{
    private String identifier;

    public ASTfieldSelection(int id)
    {
        super(id);
    }

    public ASTfieldSelection(JSONQL p, int id)
    {
        super(p, id);
    }

    public String getIdentifier()
    {
        return identifier;
    }

    public void setIdentifier(Token token)
    {
        this.identifier = token.image;
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JSONQLVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=56fa5be7887cd290c505dfcbc9b5e11b (do not edit this line) */
