/* Generated By:JJTree: Do not edit this line. ASTmatchCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.jsonql.impl;

import java.util.regex.Pattern;

import org.objectledge.jsonql.EvaluationContext;

public class ASTmatchPredicate
    extends SimpleNode
{
    private Pattern pattern;

    public ASTmatchPredicate(int id)
    {
        super(id);
    }

    public ASTmatchPredicate(JSONQL p, int id)
    {
        super(p, id);
    }

    public void setPattern(Token token)
    {
        this.pattern = Pattern.compile(token.image.substring(1, token.image.length() - 1));
    }

    public Pattern getPattern()
    {
        return pattern;
    }

    @Override
    public String toString()
    {
        return super.toString() + String.format(" ~ %s", pattern.toString());
    }

    /** Accept the visitor. **/
    public Object jjtAccept(JSONQLVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=4231a6c58b65555d9871df0cba261483 (do not edit this line) */
