/* Generated By:JavaCC: Do not edit this line. CronParserConstants.java */
package org.objectledge.scheduler.cron;

public interface CronParserConstants {

  int EOF = 0;
  int DIGIT = 3;
  int NUMBER = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<DIGIT>",
    "<NUMBER>",
    "\"-\"",
    "\"/\"",
    "\",\"",
    "\"*\"",
    "\"jan\"",
    "\"feb\"",
    "\"mar\"",
    "\"apr\"",
    "\"may\"",
    "\"jun\"",
    "\"jul\"",
    "\"aug\"",
    "\"sep\"",
    "\"oct\"",
    "\"nov\"",
    "\"dec\"",
    "\"mon\"",
    "\"tue\"",
    "\"wed\"",
    "\"thu\"",
    "\"fri\"",
    "\"sat\"",
    "\"sun\"",
    "\"@reboot\"",
    "\"@yearly\"",
    "\"@annually\"",
    "\"@monthly\"",
    "\"@daily\"",
    "\"@midnight\"",
    "\"@hourly\"",
    "\"\\n\"",
  };

}
