package org.objectledge.database;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.objectledge.database.ThreadDataSource.ThreadConnection;
import org.objectledge.database.impl.DelegatingStatement;

/**
 * Statement wrapper that monitors the number of DB reads/writes, and their duration.
 *
 * @author <a href="rafal@caltha.pl">Rafał Krzewski</a>
 * @version $Id: MonitoringStatement.java,v 1.4 2005-10-10 08:57:10 rafal Exp $
 */
public class MonitoringStatement 
    extends DelegatingStatement
{
    private final ThreadConnection threadConn;

    /**
     * Creates a new MonitoringStatement instance.
     *
     * @param statement original Statement.
     * @param threadConn associated ThreadConnection.
     */
    public MonitoringStatement(Statement statement, ThreadConnection threadConn)
    {
        super(statement);
        this.threadConn = threadConn;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean execute(String sql, int autoGeneratedKeys)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.execute(sql, autoGeneratedKeys);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean execute(String sql, int[] columnIndexes)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.execute(sql, columnIndexes);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean execute(String sql, String[] columnNames)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.execute(sql, columnNames);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean execute(String sql)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.execute(sql);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultSet executeQuery(String sql)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.executeQuery(sql);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.executeUpdate(sql, autoGeneratedKeys);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int executeUpdate(String sql, int[] columnIndexes)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.executeUpdate(sql, columnIndexes);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int executeUpdate(String sql, String[] columnNames)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.executeUpdate(sql, columnNames);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int executeUpdate(String sql)
        throws SQLException
    {
        threadConn.startStatement(sql);
        try
        {
            return super.executeUpdate(sql);
        }
        finally
        {
            threadConn.finishStatement(sql);
        }
    }
    
    
    /**
     * {@inheritDoc}
     */
    @Override
    public int[] executeBatch()
        throws SQLException
    {
        threadConn.startStatement(getBatchBuffer());
        try
        {
            return super.executeBatch();
        }
        finally
        {
            threadConn.finishStatement(getBatchBuffer());
        }
    }
}