/* Generated By:JJTree: Do not edit this line. ASTconjunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

import org.objectledge.web.ratelimit.rules.RateLimitRules;
import org.objectledge.web.ratelimit.rules.RateLimitRulesVisitor;

public
class ASTconjunction extends SimpleNode {
  public ASTconjunction(int id) {
    super(id);
  }

  public ASTconjunction(RateLimitRules p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public boolean jjtAccept(RateLimitRulesVisitor visitor, EvaluationContext data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4cbfd64d9901a5c599ec5abf72da6da3 (do not edit this line) */
