/* Generated By:JJTree: Do not edit this line. ASTdisjunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

import org.objectledge.web.ratelimit.rules.RateLimitRules;
import org.objectledge.web.ratelimit.rules.RateLimitRulesVisitor;

public
class ASTdisjunction extends SimpleNode {
  public ASTdisjunction(int id) {
    super(id);
  }

  public ASTdisjunction(RateLimitRules p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RateLimitRulesVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b937176715ecfee154ffa844f6b68c41 (do not edit this line) */
