/* Generated By:JJTree: Do not edit this line. ASTpredicateIp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

import java.net.InetAddress;
import java.net.UnknownHostException;

import org.objectledge.net.IPAddressUtil;

public class ASTpredicateIp
    extends SimpleNode
{
    private InetAddress address;

    public ASTpredicateIp(int id)
    {
        super(id);
    }

    public ASTpredicateIp(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setAddress(Token t)
        throws ParseException
    {
        try
        {
            address = IPAddressUtil.byAddress(t.image);
        }
        catch(UnknownHostException | IllegalArgumentException e)
        {
            throw new ParseException("Invalid IP address at line " + t.beginLine + " column "
                + t.beginColumn + ": " + e.getMessage());
        }
    }

    public InetAddress getAddress()
    {
        return address;
    }

    /** Accept the visitor. **/
    public Object jjtAccept(RateLimitRulesVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=72690bb64aa30738219426484097a714 (do not edit this line) */
