/* Generated By:JJTree: Do not edit this line. ASTpredicateHeaderMatch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

public class ASTpredicateHeaderMatch
    extends SimpleNode
{

    private String header;

    private Pattern pattern;

    public ASTpredicateHeaderMatch(int id)
    {
        super(id);
    }

    public ASTpredicateHeaderMatch(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setHeader(Token t)
    {
        header = t.image;
    }

    public String getHeader()
    {
        return header;
    }

    public void setPattern(Token t)
        throws ParseException
    {
        try
        {
            pattern = Pattern.compile(t.image.substring(1, t.image.length() - 1));
        }
        catch(PatternSyntaxException e)
        {
            throw new ParseException("Invalid pattern at line " + t.beginLine + " column "
                + t.beginColumn + ": " + e.getMessage());
        }
    }

    public Pattern getPattern()
    {
        return pattern;
    }

    /** Accept the visitor. **/
    public boolean jjtAccept(RateLimitRulesVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=7d9fc981b5e05ce71a3830b502a29f68 (do not edit this line) */
