/* Generated By:JJTree: Do not edit this line. ASTpredicateIpMatch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

import java.net.InetAddress;
import java.net.UnknownHostException;

import org.objectledge.net.CIDRBlock;
import org.objectledge.net.IPAddressUtil;

public class ASTpredicateIpMatch
    extends SimpleNode
{
    private CIDRBlock block;

    public ASTpredicateIpMatch(int id)
    {
        super(id);
    }

    public ASTpredicateIpMatch(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setAddressBlock(Token address, Token length)
        throws ParseException
    {
        try
        {
            InetAddress addr = IPAddressUtil.byAddress(address.image);
            int prefixLenth = Integer.parseInt(length.image);
            try
            {
                block = new CIDRBlock(addr, prefixLenth);
            }
            catch(IllegalArgumentException e)
            {
                throw new ParseException("Invalid address block specification at line "
                    + length.beginLine + " column " + length.beginColumn + ": " + e.getMessage());
            }
        }
        catch(NumberFormatException e)
        {
            throw new ParseException("Invalid prefix length at line " + length.beginLine
                + " column " + length.beginColumn + ": " + e.getMessage());
        }
        catch(UnknownHostException | IllegalArgumentException e)
        {
            throw new ParseException("Invalid IP address at line " + address.beginLine + " column "
                + address.beginColumn + ": " + e.getMessage());
        }
    }

    public CIDRBlock getAddressBlock()
    {
        return block;
    }

    /** Accept the visitor. **/
    public boolean jjtAccept(RateLimitRulesVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=5dccc236948edb47fcb76b0577decfe0 (do not edit this line) */
