/* Generated By:JJTree: Do not edit this line. ASTpredicateHost.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

public class ASTpredicateHost
    extends SimpleNode
{

    private String name;

    public ASTpredicateHost(int id)
    {
        super(id);
    }

    public ASTpredicateHost(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setName(Token t)
    {
        name = t.image.substring(1, t.image.length() - 1); // strip quotes
    }

    public String getName()
    {
        return name;
    }

    /** Accept the visitor. **/
    public boolean jjtAccept(RateLimitRulesVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=109ab9118f157c4bf870ee7a26036861 (do not edit this line) */
