/* Generated By:JJTree: Do not edit this line. ASTpredicateHeader.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;


public class ASTpredicateHeader
    extends SimpleNode
{
    private String header;
    
    private String value;
    
    public ASTpredicateHeader(int id)
    {
        super(id);
    }

    public ASTpredicateHeader(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setHeader(Token t)
    {
        header = t.image;
    }
    
    public String getHeader()
    {
        return header;
    }

    public void setValue(Token t)
    {
        value = t.image;
    }
    
    public String getValue()
    {
        return value;
    }

    /** Accept the visitor. **/
    public boolean jjtAccept(RateLimitRulesVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=c2078bba5e462d5a7ba1c3c21e2a7b10 (do not edit this line) */
