/* Generated By:JJTree: Do not edit this line. ASTpradicateHits.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;


public class ASTpredicateHits
    extends SimpleNode
{
    private int value;
    
    public ASTpredicateHits(int id)
    {
        super(id);
    }

    public ASTpredicateHits(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setValue(Token t) throws ParseException
    {
        try
        {
            value = Integer.parseInt(t.image);
        }
        catch(NumberFormatException e)
        {
            throw new ParseException("Invalid number at line " + t.beginLine + " column " + t.beginColumn);
        }
    }

    public int getValue()
    {
        return value;
    }

    /** Accept the visitor. **/
    public boolean jjtAccept(RateLimitRulesVisitor visitor, EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=94b453697535ca81d83566d4afe45a47 (do not edit this line) */
