/* Generated By:JJTree: Do not edit this line. ASTprediceteIpInList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.objectledge.web.ratelimit.rules;

public class ASTprediceteIpInList
    extends SimpleNode
{
    private String listName;
    
    public ASTprediceteIpInList(int id)
    {
        super(id);
    }

    public ASTprediceteIpInList(RateLimitRules p, int id)
    {
        super(p, id);
    }

    public void setListName(Token token)
    {
        listName = token.image;
    }

    public String getListName()
    {
        return listName;
    }

    /** Accept the visitor. **/
    public boolean jjtAccept(RateLimitRulesVisitor visitor,
        org.objectledge.web.ratelimit.rules.EvaluationContext data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=d8f8b9c8f140d8bba1e45a4505226fd8 (do not edit this line) */
